trailingComma: "all"
tabWidth: 2
semi: true
singleQuote: true
jsxSingleQuote: true
bracketSameLine: false
printWidth: 80
overrides:
  - files: ".{j,t}s{,x}"
    options:
      semi: true
      parser: typescript
